#
# markdownlint-cli2.yaml configuration file
#

extends: default

config:
  # MD012/no-multiple-blanks MD012 - Multiple consecutive blank lines : https://github.com/DavidAnson/markdownlint/blob/main/doc/md012.md
  MD012:
    maximum: 2

  # MD013/line-length : Line length : https://github.com/DavidAnson/markdownlint/blob/main/doc/md013.md
  MD013:
    # Number of characters
    line_length: 120
    # Number of characters for headings
    heading_line_length: 80
    # Number of characters for code blocks
    code_block_line_length: 80
    # Include code blocks
    code_blocks: false
    # Include tables
    tables: false
    # Include headings
    headings: true
    # Strict length checking
    strict: false
    # Stern length checking
    stern: false

  # MD026/no-trailing-punctuation Trailing punctuation in heading : https://github.com/DavidAnson/markdownlint/blob/main/doc/md026.md
  MD026:
    punctuation: ".,;:-"
