name: 👥 Update contributors family

on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:
    # Allows manual triggering from the GitHub Actions tab

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    name: Update contributors family
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: update-contributors
        name: Update contributors family
        uses: akhilmhdh/contributors-readme-action@v2.3.10
        with:
          readme_path: docs/CONTRIBUTORS.md
          commit_message: 'docs: update contributors family'
          pr_title_on_protected: 'docs: Update contributors family'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
